[deps]
AbstractMCMC = "80f14c24-f653-4e6a-9b94-39d6b0f70001"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DEMetropolis = "b4be8cd2-ef9b-406c-8da0-f1f18fb2b05e"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"

[sources]
DEMetropolis = {path = "./.."}
