name = "DEMetropolis"
uuid = "b4be8cd2-ef9b-406c-8da0-f1f18fb2b05e"
authors = ["Greg Barnsley <gregory.barnsley@lshtm.ac.uk>"]
version = "1.0.0"

[deps]
AbstractMCMC = "80f14c24-f653-4e6a-9b94-39d6b0f70001"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
AbstractMCMC = "5.8.0"
Aqua = "0.8"
Distributions = "0.25"
LogDensityProblems = "2.1"
Random = "1.6"
StatsBase = "0.34"
Test = "1"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua"]
