name = "DEMetropolis"
uuid = "b4be8cd2-ef9b-406c-8da0-f1f18fb2b05e"
version = "2.0.0"
authors = ["Greg Barnsley <gregory.barnsley@lshtm.ac.uk>"]

[deps]
AbstractMCMC = "80f14c24-f653-4e6a-9b94-39d6b0f70001"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
MCMCDiagnosticTools = "be115224-59cd-429b-ad48-344e309966f0"

[weakdeps]
MCMCDiagnosticTools = "be115224-59cd-429b-ad48-344e309966f0"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"

[extensions]
MCMCDiagnosticToolsExt = "MCMCDiagnosticTools"
MCMCChainsExt = "MCMCChains"

[compat]
AbstractMCMC = "5.8"
Aqua = "0.8"
Distributions = "0.25"
LinearAlgebra = "1.6"
LogDensityProblems = "2.1"
Logging = "1.6"
MCMCChains = "7.5"
MCMCDiagnosticTools = "0.1, 0.2, 0.3"
Random = "1.6"
StatsBase = "0.34"
Test = "1"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MCMCDiagnosticTools = "be115224-59cd-429b-ad48-344e309966f0"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"

[targets]
test = ["Test", "Aqua", "Logging", "MCMCDiagnosticTools", "MCMCChains"]
